-- MySQL Script generated by MySQL Workbench
-- Thu Apr 10 16:20:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema varehusdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema varehusdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `varehusdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `varehusdb` ;

-- -----------------------------------------------------
-- Table `varehusdb`.`poststed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varehusdb`.`poststed` (
  `PostNr` CHAR(4) NOT NULL,
  `Poststed` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PostNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `varehusdb`.`ansatt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varehusdb`.`ansatt` (
  `AnsNr` SMALLINT NOT NULL,
  `Fornavn` VARCHAR(50) NOT NULL,
  `Etternavn` VARCHAR(50) NOT NULL,
  `Adresse` VARCHAR(100) NULL DEFAULT NULL,
  `PostNr` CHAR(4) NOT NULL,
  `Fødselsdato` DATE NULL DEFAULT NULL,
  `Stilling` VARCHAR(50) NULL DEFAULT NULL,
  `Årslønn` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`AnsNr`),
  INDEX `AnsattPoststedFN` (`PostNr` ASC) VISIBLE,
  CONSTRAINT `AnsattPoststedFN`
    FOREIGN KEY (`PostNr`)
    REFERENCES `varehusdb`.`poststed` (`PostNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `varehusdb`.`kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varehusdb`.`kategori` (
  `KatNr` SMALLINT NOT NULL,
  `Navn` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`KatNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `varehusdb`.`kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varehusdb`.`kunde` (
  `KNr` INT NOT NULL,
  `Fornavn` VARCHAR(50) NOT NULL,
  `Etternavn` VARCHAR(50) NOT NULL,
  `Adresse` VARCHAR(100) NOT NULL,
  `PostNr` CHAR(4) NOT NULL,
  PRIMARY KEY (`KNr`),
  INDEX `KundePoststedFN` (`PostNr` ASC) VISIBLE,
  CONSTRAINT `KundePoststedFN`
    FOREIGN KEY (`PostNr`)
    REFERENCES `varehusdb`.`poststed` (`PostNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `varehusdb`.`ordre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varehusdb`.`ordre` (
  `OrdreNr` INT NOT NULL,
  `OrdreDato` DATE NOT NULL,
  `SendtDato` DATE NULL DEFAULT NULL,
  `BetaltDato` DATE NULL DEFAULT NULL,
  `KNr` INT NOT NULL,
  PRIMARY KEY (`OrdreNr`),
  INDEX `OrdreKundeFN` (`KNr` ASC) VISIBLE,
  CONSTRAINT `OrdreKundeFN`
    FOREIGN KEY (`KNr`)
    REFERENCES `varehusdb`.`kunde` (`KNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `varehusdb`.`vare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varehusdb`.`vare` (
  `VNr` CHAR(5) NOT NULL,
  `Betegnelse` VARCHAR(100) NOT NULL,
  `Pris` DECIMAL(8,2) NOT NULL,
  `KatNr` SMALLINT NULL DEFAULT NULL,
  `Antall` INT NOT NULL,
  `Hylle` CHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`VNr`),
  INDEX `VareKategoriFN` (`KatNr` ASC) VISIBLE,
  CONSTRAINT `VareKategoriFN`
    FOREIGN KEY (`KatNr`)
    REFERENCES `varehusdb`.`kategori` (`KatNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `varehusdb`.`ordrelinje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varehusdb`.`ordrelinje` (
  `OrdreNr` INT NOT NULL,
  `VNr` CHAR(5) NOT NULL,
  `PrisPrEnhet` DECIMAL(8,2) NOT NULL,
  `Antall` INT NOT NULL,
  PRIMARY KEY (`OrdreNr`, `VNr`),
  INDEX `OrdrelinjeVareFN` (`VNr` ASC) VISIBLE,
  CONSTRAINT `OrdrelinjeOrdreFN`
    FOREIGN KEY (`OrdreNr`)
    REFERENCES `varehusdb`.`ordre` (`OrdreNr`),
  CONSTRAINT `OrdrelinjeVareFN`
    FOREIGN KEY (`VNr`)
    REFERENCES `varehusdb`.`vare` (`VNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `varehusdb`.`prishistorikk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `varehusdb`.`prishistorikk` (
  `VNr` CHAR(5) NOT NULL,
  `Dato` DATE NOT NULL,
  `GammelPris` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`VNr`, `Dato`),
  CONSTRAINT `PrishistorikkVareFN`
    FOREIGN KEY (`VNr`)
    REFERENCES `varehusdb`.`vare` (`VNr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `varehusdb` ;

-- -----------------------------------------------------
-- procedure ShowInventory
-- -----------------------------------------------------

DELIMITER $$
USE `varehusdb`$$
CREATE DEFINER=`root`@`%` PROCEDURE `ShowInventory`()
BEGIN
    SELECT * FROM ordre;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
